### ISSUE TITLE
Android - when calling NativeScreenshot.takeScreenshotImage i got this error 

### ISSUE THREAD

**Issue by ttzein6** [gdagitrep/native_screenshot_ext#4]
```

E/MethodChannel#native_screenshot_ext(16789): Failed to handle method call
E/MethodChannel#native_screenshot_ext(16789): java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.ArrayList
E/MethodChannel#native_screenshot_ext(16789): 	at jpg.ivan.native_screenshot.NativeScreenshotPlugin.onMethodCall(NativeScreenshotPlugin.java:143)
E/MethodChannel#native_screenshot_ext(16789): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#native_screenshot_ext(16789): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#native_screenshot_ext(16789): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#native_screenshot_ext(16789): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#native_screenshot_ext(16789): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#native_screenshot_ext(16789): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#native_screenshot_ext(16789): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#native_screenshot_ext(16789): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#native_screenshot_ext(16789): 	at android.app.ActivityThread.main(ActivityThread.java:8741)
E/MethodChannel#native_screenshot_ext(16789): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#native_screenshot_ext(16789): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#native_screenshot_ext(16789): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
[log] Catched Error : PlatformException(error, java.util.HashMap cannot be cast to java.util.ArrayList, null, java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.ArrayList
      	at jpg.ivan.native_screenshot.NativeScreenshotPlugin.onMethodCall(NativeScreenshotPlugin.java:143)
      	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
      	at android.os.Handler.handleCallback(Handler.java:942)
      	at android.os.Handler.dispatchMessage(Handler.java:99)
      	at android.os.Looper.loopOnce(Looper.java:226)
      	at android.os.Looper.loop(Looper.java:313)
      	at android.app.ActivityThread.main(ActivityThread.java:8741)
      	at java.lang.reflect.Method.invoke(Native Method)
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
      )


```

**Comment by ttzein6** [comment]
I am using the package like that
![Screenshot 2023-10-27 at 4 21 34 PM](https://github.com/gdagitrep/native_screenshot_ext/assets/72082671/0af3608d-09ac-44dd-824c-a52aae47fd4a)

**Comment by K123Ritesh** [comment]
@ttzein6 is taking screen shot working for > Android 13
